(function(){
  const state={docs:[],rates:{overdue:100,b0:100,b1:100,b2:100,b3:100},currency:'TODAS',portfolio:'TODAS',seller:'TODOS',days:90};
  const escFC=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const moneyFC=(n,m)=>Number(n||0).toLocaleString('es-PY',{minimumFractionDigits:m==='USD'?2:0,maximumFractionDigits:m==='USD'?2:0});
  const dateFC=s=>{if(!s)return null;const [y,mo,d]=String(s).slice(0,10).split('-').map(Number);return y&&mo&&d?new Date(y,mo-1,d):null};
  const todayFC=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
  const diffFC=(a,b)=>Math.round((a-b)/86400000);
  function view(){return document.getElementById('view-flujo')}
  function renderShell(){
    const v=view();if(!v)return;
    v.innerHTML=`<div class="section-title"><h2>Flujo de Caja</h2><p>Proyección de posibles ingresos por cobranzas según los vencimientos de las carteras. Esta pantalla es independiente y no modifica los datos existentes.</p></div>
      <div class="card"><div class="section-head"><h3>Parámetros de proyección</h3><div class="fc-controls">
          <select id="fcCurrency"><option value="TODAS">Todas las monedas</option><option value="USD">USD</option><option value="GS">GS</option></select>
          <select id="fcPortfolio"><option value="TODAS">Todas las carteras</option></select>
          <select id="fcSeller"><option value="TODOS">Todos los vendedores</option></select>
          <select id="fcDays"><option value="30">30 días</option><option value="60">60 días</option><option value="90" selected>90 días</option><option value="180">180 días</option><option value="365">365 días</option></select>
        </div></div>
        <div class="fc-rate-grid"><label>Vencido <input id="fcRateOverdue" type="number" min="0" max="100" step="1" value="100"> %</label><label>0–30 días <input id="fcRate0" type="number" min="0" max="100" step="1" value="100"> %</label><label>31–60 días <input id="fcRate1" type="number" min="0" max="100" step="1" value="100"> %</label><label>61–90 días <input id="fcRate2" type="number" min="0" max="100" step="1" value="100"> %</label><label>+90 días <input id="fcRate3" type="number" min="0" max="100" step="1" value="100"> %</label></div>
        <div class="status">Las tasas son parámetros de simulación: <b>no cambian la cartera ni se guardan en la base de datos</b>. Con 100% se muestra el potencial nominal.</div>
      </div>
      <div id="fcMetrics" class="grid-4"></div>
      <div class="card"><div class="section-head"><h3>Proyección de ingresos</h3><span id="fcAsOf" class="status-inline"></span></div><div class="table-wrap"><table class="report"><thead><tr><th>Período</th><th>Moneda</th><th>Saldo nominal</th><th>Tasa</th><th>Cobranza estimada</th></tr></thead><tbody id="fcBody"></tbody></table></div></div>
      <div class="card"><div class="section-head"><h3>Detalle por vencimiento</h3><span>Solo documentos vigentes</span></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Moneda</th><th>Cartera</th><th>Cliente</th><th>Vendedor</th><th>Saldo</th><th>Situación</th></tr></thead><tbody id="fcDetailBody"></tbody></table></div></div>`;
    const p=document.getElementById('fcPortfolio');(carteras||[]).forEach(c=>{p.insertAdjacentHTML('beforeend',`<option value="${c.id}">${escFC(c.nombre)} (${escFC(c.moneda)})</option>`)});
    const s=document.getElementById('fcSeller');(vendedores||[]).forEach(x=>{s.insertAdjacentHTML('beforeend',`<option value="${x.id}">${escFC(x.nombre)}</option>`)});
    ['fcCurrency','fcPortfolio','fcSeller','fcDays','fcRateOverdue','fcRate0','fcRate1','fcRate2','fcRate3'].forEach(id=>document.getElementById(id).addEventListener('input',apply));
    document.getElementById('fcPortfolio').addEventListener('change',apply);document.getElementById('fcSeller').addEventListener('change',apply);document.getElementById('fcDays').addEventListener('change',apply);apply();
  }
  async function load(){if(!view())return;renderShell();const{data,error}=await sb.from('documentos_cartera').select('id,cartera_id,cliente_id,vendedor_actual_id,vendedor_origen,cliente:cartera_clientes(nombre,codigo),vendedor:cartera_vendedores(nombre),vencimiento,saldo,estado').eq('estado','VIGENTE').range(0,9999);if(error){console.error(error);const b=document.getElementById('fcDetailBody');if(b)b.innerHTML='<tr><td colspan="7">No se pudieron cargar los documentos para la proyección.</td></tr>';return}state.docs=data||[];apply();}
  function rates(){return{overdue:Math.max(0,Math.min(100,Number(document.getElementById('fcRateOverdue')?.value||100))),b0:Math.max(0,Math.min(100,Number(document.getElementById('fcRate0')?.value||100))),b1:Math.max(0,Math.min(100,Number(document.getElementById('fcRate1')?.value||100))),b2:Math.max(0,Math.min(100,Number(document.getElementById('fcRate2')?.value||100))),b3:Math.max(0,Math.min(100,Number(document.getElementById('fcRate3')?.value||100)))}}
  function classify(d,t){if(!d)return{key:'b3',label:'+90 días',rate:'b3',diff:null};const n=diffFC(d,t);if(n<0)return{key:'overdue',label:'Vencido',rate:'overdue',diff:n};if(n<=30)return{key:'b0',label:'0–30 días',rate:'b0',diff:n};if(n<=60)return{key:'b1',label:'31–60 días',rate:'b1',diff:n};if(n<=90)return{key:'b2',label:'61–90 días',rate:'b2',diff:n};return{key:'b3',label:'+90 días',rate:'b3',diff:n}}
  function filtered(){const cur=document.getElementById('fcCurrency')?.value||'TODAS',pid=document.getElementById('fcPortfolio')?.value||'TODAS',sid=document.getElementById('fcSeller')?.value||'TODOS';return state.docs.filter(x=>{const c=(carteras||[]).find(z=>String(z.id)===String(x.cartera_id));if(cur!=='TODAS'&&c?.moneda!==cur)return false;if(pid!=='TODAS'&&String(x.cartera_id)!==String(pid))return false;if(sid!=='TODOS'&&String(x.vendedor_actual_id||'')!==String(sid))return false;return true}).map(x=>({...x,_c:(carteras||[]).find(z=>String(z.id)===String(x.cartera_id))}));}
  function apply(){if(!document.getElementById('fcBody'))return;const docs=filtered(),t=todayFC(),r=rates(),days=Number(document.getElementById('fcDays').value||90),agg=new Map(),detail=[];['USD','GS'].forEach(()=>{});
    docs.forEach(x=>{const d=dateFC(x.vencimiento),a=classify(d,t),m=x._c?.moneda||'USD',amt=Number(x.saldo||0);if(a.diff===null||a.diff<0||a.diff<=days){const k=a.key+'|'+m;if(!agg.has(k))agg.set(k,{label:a.label,key:a.key,m,nom:0,exp:0,rate:r[a.rate]});agg.get(k).nom+=amt;agg.get(k).exp+=amt*r[a.rate]/100;}detail.push({x,a,d,amt});});
    const metrics=[];['USD','GS'].forEach(m=>{const ds=docs.filter(x=>(x._c?.moneda||'USD')===m);if(!ds.length)return;const tot=ds.reduce((a,x)=>a+Number(x.saldo||0),0),ov=ds.reduce((a,x)=>{const d=dateFC(x.vencimiento);return d&&d<t?a+Number(x.saldo||0):a},0),n30=ds.reduce((a,x)=>{const d=dateFC(x.vencimiento),n=d?diffFC(d,t):9999;return n>=0&&n<=30?a+Number(x.saldo||0):a},0),exp=ds.reduce((a,x)=>{const z=classify(dateFC(x.vencimiento),t);return z.diff===null||z.diff<0||z.diff<=days?a+Number(x.saldo||0)*r[z.rate]/100:a},0);metrics.push(`<div class="metric"><small>Total ${m}</small><strong>${moneyFC(tot,m)}</strong><span>Vencido: ${moneyFC(ov,m)} · Próx. 30 días: ${moneyFC(n30,m)}</span><span>Ingreso estimado (${days} días): <b>${moneyFC(exp,m)}</b></span></div>`)});
    document.getElementById('fcMetrics').innerHTML=metrics.join('');document.getElementById('fcAsOf').textContent=`Base: ${t.toLocaleDateString('es-PY')} · ${docs.length} documentos`;
    const order={overdue:0,b0:1,b1:2,b2:3,b3:4};const rows=[...agg.values()].sort((a,b)=>order[a.key]-order[b.key]||a.m.localeCompare(b.m));document.getElementById('fcBody').innerHTML=rows.length?rows.map(a=>`<tr><td>${a.label}</td><td>${a.m}</td><td>${moneyFC(a.nom,a.m)}</td><td>${a.rate.toFixed(0)}%</td><td>${moneyFC(a.exp,a.m)}</td></tr>`).join(''):'<tr><td colspan="5">No hay datos con los filtros seleccionados.</td></tr>';
    detail.sort((a,b)=>(a.d?.getTime()||0)-(b.d?.getTime()||0));document.getElementById('fcDetailBody').innerHTML=detail.filter(z=>z.a.diff===null||z.a.diff<0||z.a.diff<=days).map(z=>`<tr><td>${z.d?z.d.toLocaleDateString('es-PY'):''}</td><td>${z.x._c?.moneda||'USD'}</td><td>${escFC(z.x._c?.nombre||'')}</td><td>${escFC(z.x.cliente?.nombre||'')}</td><td>${escFC(z.x.vendedor?.nombre||'SIN VENDEDOR')}</td><td>${moneyFC(z.amt,z.x._c?.moneda||'USD')}</td><td>${z.a.label}</td></tr>`).join('')||'<tr><td colspan="7">No hay documentos dentro del período seleccionado.</td></tr>';
  }
  document.addEventListener('click',e=>{const b=e.target.closest('.tab[data-view="flujo"]');if(b)setTimeout(load,0)});window.loadFlujoCaja=load;
})();