(function(){
  const state={docs:[],rates:{overdue:100,b0:100,b1:100,b2:100,b3:100},currency:'TODAS',portfolio:'TODAS',seller:'TODOS',days:90};
  const escFC=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const moneyFC=(n,m)=>Number(n||0).toLocaleString('es-PY',{minimumFractionDigits:m==='USD'?2:0,maximumFractionDigits:m==='USD'?2:0});
  const dateFC=s=>{if(!s)return null;const [y,mo,d]=String(s).slice(0,10).split('-').map(Number);return y&&mo&&d?new Date(y,mo-1,d):null};
  const todayFC=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
  const diffFC=(a,b)=>Math.round((a-b)/86400000);
  function view(){return document.getElementById('view-flujo')}
  function monedaDoc(x){const m=String(x?.moneda||'').trim().toUpperCase();if(m==='GS'||m==='G$'||m==='PYG'||m==='GUARANIES')return'GS';if(m==='USD'||m==='US$'||m==='$')return'USD';return String(x?._c?.moneda||'').trim().toUpperCase()==='GS'?'GS':'USD'}
  function carteraDoc(x){return (carteras||[]).find(z=>String(z.id)===String(x.cartera_id))||null}
  function antiguedadFC(d,t){if(!d)return'';const n=diffFC(d,t);if(n<0)return `${Math.abs(n)} días vencidos`;if(n===0)return 'Vence hoy';return `${n} días por vencer`}
  function renderShell(){
    const v=view();if(!v)return;
    v.innerHTML=`<div class="section-title"><h2>Flujo de Caja</h2><p>Proyección de posibles ingresos por cobranzas según los vencimientos de las carteras. Esta pantalla es independiente y no modifica los datos existentes.</p></div>
      <div class="card"><div class="section-head"><h3>Parámetros de proyección</h3><div class="fc-controls">
          <select id="fcCurrency"><option value="TODAS">Todas las monedas</option><option value="USD">USD</option><option value="GS">GS</option></select>
          <select id="fcPortfolio"><option value="TODAS">Todas las carteras</option></select>
          <select id="fcSeller"><option value="TODOS">Todos los vendedores</option></select>
          <select id="fcDays"><option value="30">30 días</option><option value="60">60 días</option><option value="90" selected>90 días</option><option value="180">180 días</option><option value="365">365 días</option></select>
        </div></div>
        <div class="fc-rate-grid"><label>Vencido <input id="fcRateOverdue" type="number" min="0" max="100" step="1" value="100"> %</label><label>0–30 días <input id="fcRate0" type="number" min="0" max="100" step="1" value="100"> %</label><label>31–60 días <input id="fcRate1" type="number" min="0" max="100" step="1" value="100"> %</label><label>61–90 días <input id="fcRate2" type="number" min="0" max="100" step="1" value="100"> %</label><label>+90 días <input id="fcRate3" type="number" min="0" max="100" step="1" value="100"> %</label></div>
        <div class="status">Las tasas son parámetros de simulación: <b>no cambian la cartera ni se guardan en la base de datos</b>. Con 100% se muestra el potencial nominal.</div>
      </div>
      <div id="fcMetrics" class="grid-4"></div>
      <div class="card"><div class="section-head"><h3>Proyección de ingresos</h3><span id="fcAsOf" class="status-inline"></span></div>
        <div class="fc-projection-grid">
          <div class="fc-projection-block"><h3>Proyección de ingresos USD</h3><div class="table-wrap"><table class="report"><thead><tr><th>Período</th><th>Saldo nominal</th><th>Tasa</th><th>Cobranza estimada</th></tr></thead><tbody id="fcBodyUSD"></tbody></table></div><div class="fc-projection-total" style="display:flex;align-items:center;justify-content:space-between;gap:40px;"><span>TOTAL COBRANZA ESTIMADA USD</span><strong id="fcEstimatedUSD" style="margin-left:auto;white-space:nowrap;">0,00</strong></div></div>
          <div class="fc-projection-block"><h3>Proyección de ingresos GS</h3><div class="table-wrap"><table class="report"><thead><tr><th>Período</th><th>Saldo nominal</th><th>Tasa</th><th>Cobranza estimada</th></tr></thead><tbody id="fcBodyGS"></tbody></table></div><div class="fc-projection-total" style="display:flex;align-items:center;justify-content:space-between;gap:40px;"><span>TOTAL COBRANZA ESTIMADA GS</span><strong id="fcEstimatedGS" style="margin-left:auto;white-space:nowrap;">0</strong></div></div>
        </div>
      </div>
      <div class="card"><div class="section-head"><h3>Vencimientos por tramo</h3><span>Seleccione un tramo para ver clientes y montos</span></div><div id="fcTranches"></div></div>
      <div class="card" id="fcOverdueAlertCard"><div class="section-head"><h3>⚠ Clientes con vencimientos</h3><span id="fcOverdueCount" class="status-inline"></span></div><div id="fcOverdueAlert" class="status"></div><div class="table-wrap"><table class="report"><thead><tr><th>Cliente</th><th>Moneda</th><th>Cartera</th><th>Saldo vencido</th><th>Vencimiento más antiguo</th><th>Antigüedad</th></tr></thead><tbody id="fcOverdueBody"></tbody></table></div></div>`;
    const p=document.getElementById('fcPortfolio');(carteras||[]).forEach(c=>{p.insertAdjacentHTML('beforeend',`<option value="${c.id}">${escFC(c.nombre)} (${escFC(c.moneda)})</option>`)});
    const s=document.getElementById('fcSeller');(vendedores||[]).forEach(x=>{s.insertAdjacentHTML('beforeend',`<option value="${x.id}">${escFC(x.nombre)}</option>`)});
    ['fcCurrency','fcPortfolio','fcSeller','fcDays','fcRateOverdue','fcRate0','fcRate1','fcRate2','fcRate3'].forEach(id=>document.getElementById(id).addEventListener('input',apply));
    document.getElementById('fcPortfolio').addEventListener('change',apply);document.getElementById('fcSeller').addEventListener('change',apply);document.getElementById('fcDays').addEventListener('change',apply);apply();
  }
  async function load(){if(!view())return;renderShell();const{data,error}=await sb.from('documentos_cartera').select('id,cartera_id,cliente_id,vendedor_actual_id,vendedor_origen,moneda,cliente:cartera_clientes(nombre,codigo),vendedor:cartera_vendedores(nombre),vencimiento,saldo,estado').eq('estado','VIGENTE').range(0,9999);if(error){console.error(error);const b=document.getElementById('fcTranches');if(b)b.innerHTML='<div class="status">No se pudieron cargar los documentos para la proyección.</div>';return}state.docs=(data||[]).map(x=>({...x,_c:carteraDoc(x)}));apply();}
  function rates(){return{overdue:Math.max(0,Math.min(100,Number(document.getElementById('fcRateOverdue')?.value||100))),b0:Math.max(0,Math.min(100,Number(document.getElementById('fcRate0')?.value||100))),b1:Math.max(0,Math.min(100,Number(document.getElementById('fcRate1')?.value||100))),b2:Math.max(0,Math.min(100,Number(document.getElementById('fcRate2')?.value||100))),b3:Math.max(0,Math.min(100,Number(document.getElementById('fcRate3')?.value||100)))}}
  function classify(d,t){if(!d)return{key:'b3',label:'+90 días',rate:'b3',diff:null};const n=diffFC(d,t);if(n<0)return{key:'overdue',label:'Vencido',rate:'overdue',diff:n};if(n<=30)return{key:'b0',label:'0–30 días',rate:'b0',diff:n};if(n<=60)return{key:'b1',label:'31–60 días',rate:'b1',diff:n};if(n<=90)return{key:'b2',label:'61–90 días',rate:'b2',diff:n};return{key:'b3',label:'+90 días',rate:'b3',diff:n}}
  function filtered(){const cur=document.getElementById('fcCurrency')?.value||'TODAS',pid=document.getElementById('fcPortfolio')?.value||'TODAS',sid=document.getElementById('fcSeller')?.value||'TODOS';return state.docs.filter(x=>{const m=monedaDoc(x);if(cur!=='TODAS'&&m!==cur)return false;if(pid!=='TODAS'&&String(x.cartera_id)!==String(pid))return false;if(sid!=='TODOS'&&String(x.vendedor_actual_id||'')!==String(sid))return false;return true}).map(x=>({...x,_c:x._c||carteraDoc(x),_m:monedaDoc(x)}));}
  function groupClients(items){const map=new Map();items.forEach(z=>{const name=z.x.cliente?.nombre||'SIN CLIENTE',key=[name,z.m,z.x.cartera_id].join('|');let g=map.get(key);if(!g){g={cliente:name,m:z.m,cartera:z.x._c?.nombre||'',saldo:0,fecha:z.d};map.set(key,g)}g.saldo+=z.amt;if(z.d&&(!g.fecha||z.d<g.fecha))g.fecha=z.d});return [...map.values()].sort((a,b)=>a.m.localeCompare(b.m)||b.saldo-a.saldo||String(a.cliente).localeCompare(String(b.cliente)))}
  function trancheMarkup(key,label,items,t){
    const byM=['USD','GS'].map(m=>{const total=items.filter(z=>z.m===m).reduce((a,z)=>a+z.amt,0);return total?`<span>${m}: <b>${moneyFC(total,m)}</b></span>`:''}).filter(Boolean).join(' · ');
    const clients=groupClients(items);const rows=clients.length?clients.map(g=>`<tr><td>${escFC(g.cliente)}</td><td>${g.m}</td><td>${escFC(g.cartera)}</td><td>${moneyFC(g.saldo,g.m)}</td><td>${g.fecha?g.fecha.toLocaleDateString('es-PY'):''}</td><td>${antiguedadFC(g.fecha,t)}</td></tr>`).join(''):'<tr><td colspan="6">No hay vencimientos en este tramo.</td></tr>';
    return `<details class="fc-tranche" ${key==='overdue'?'open':''}><summary><span><b>${label}</b> <small>· ${clients.length} clientes</small></span><span>${byM||'Sin saldo'}</span></summary><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Moneda</th><th>Cartera</th><th>Monto</th><th>Vencimiento</th><th>Antigüedad</th></tr></thead><tbody>${rows}</tbody></table></div></details>`;
  }
  function apply(){if(!document.getElementById('fcBodyUSD'))return;const docs=filtered(),t=todayFC(),r=rates(),days=Number(document.getElementById('fcDays').value||90),agg=new Map(),detail=[];
    docs.forEach(x=>{const d=dateFC(x.vencimiento),a=classify(d,t),m=x._m||monedaDoc(x),amt=Number(x.saldo||0);if(a.diff===null||a.diff<0||a.diff<=days){const k=a.key+'|'+m;if(!agg.has(k))agg.set(k,{label:a.label,key:a.key,m,nom:0,exp:0,rate:r[a.rate]});agg.get(k).nom+=amt;agg.get(k).exp+=amt*r[a.rate]/100;}detail.push({x,a,d,amt,m});});
    const metrics=[];['USD','GS'].forEach(m=>{const ds=docs.filter(x=>(x._m||monedaDoc(x))===m);if(!ds.length)return;const tot=ds.reduce((a,x)=>a+Number(x.saldo||0),0),ov=ds.reduce((a,x)=>{const d=dateFC(x.vencimiento);return d&&d<t?a+Number(x.saldo||0):a},0),n30=ds.reduce((a,x)=>{const d=dateFC(x.vencimiento),n=d?diffFC(d,t):9999;return n>=0&&n<=30?a+Number(x.saldo||0):a},0),exp=ds.reduce((a,x)=>{const z=classify(dateFC(x.vencimiento),t);return z.diff===null||z.diff<0||z.diff<=days?a+Number(x.saldo||0)*r[z.rate]/100:a},0);metrics.push(`<div class="metric"><small>Total ${m}</small><strong>${moneyFC(tot,m)}</strong><span>Vencido: ${moneyFC(ov,m)} · Próx. 30 días: ${moneyFC(n30,m)}</span><span>Ingreso estimado (${days} días): <b>${moneyFC(exp,m)}</b></span></div>`)});
    document.getElementById('fcMetrics').innerHTML=metrics.join('');document.getElementById('fcAsOf').textContent=`Base: ${t.toLocaleDateString('es-PY')} · ${docs.length} registros analizados`;
    const order={overdue:0,b0:1,b1:2,b2:3,b3:4};const rows=[...agg.values()].sort((a,b)=>order[a.key]-order[b.key]||a.m.localeCompare(b.m));
    ['USD','GS'].forEach(m=>{const body=document.getElementById(`fcBody${m}`),items=rows.filter(a=>a.m===m);body.innerHTML=items.length?items.map(a=>`<tr><td>${a.label}</td><td>${moneyFC(a.nom,m)}</td><td>${a.rate.toFixed(0)}%</td><td>${moneyFC(a.exp,m)}</td></tr>`).join(''):'<tr><td colspan="4">No hay datos con los filtros seleccionados.</td></tr>';const total=items.reduce((sum,a)=>sum+a.exp,0);document.getElementById(`fcEstimated${m}`).textContent=moneyFC(total,m)});
    const inWindow=detail.filter(z=>z.a.diff===null||z.a.diff<0||z.a.diff<=days);
    const trancheKeys=['overdue','b0','b1','b2','b3'],trancheLabels={overdue:'Vencido',b0:'0–30 días',b1:'31–60 días',b2:'61–90 días',b3:'+90 días'};
    document.getElementById('fcTranches').innerHTML=trancheKeys.filter(k=>k==='overdue'||(k==='b0'&&days>=30)||(k==='b1'&&days>=60)||(k==='b2'&&days>=90)||(k==='b3'&&days>90)).map(k=>trancheMarkup(k,trancheLabels[k],inWindow.filter(z=>z.a.key===k),t)).join('');
    const overdue=detail.filter(z=>z.a.key==='overdue'),overdueClients=groupClients(overdue);document.getElementById('fcOverdueCount').textContent=`${overdueClients.length} clientes`;
    const ovUSD=overdue.filter(z=>z.m==='USD').reduce((a,z)=>a+z.amt,0),ovGS=overdue.filter(z=>z.m==='GS').reduce((a,z)=>a+z.amt,0);document.getElementById('fcOverdueAlert').innerHTML=overdue.length?`Hay <b>${overdueClients.length} clientes</b> con saldos vencidos. ${ovUSD?`USD: <b>${moneyFC(ovUSD,'USD')}</b>. `:''}${ovGS?`GS: <b>${moneyFC(ovGS,'GS')}</b>.`:''}`:'No hay clientes con documentos vencidos en los filtros seleccionados.';
    document.getElementById('fcOverdueBody').innerHTML=overdueClients.length?overdueClients.map(g=>`<tr><td><b>${escFC(g.cliente)}</b></td><td>${g.m}</td><td>${escFC(g.cartera)}</td><td><b>${moneyFC(g.saldo,g.m)}</b></td><td>${g.fecha?g.fecha.toLocaleDateString('es-PY'):''}</td><td>${antiguedadFC(g.fecha,t)}</td></tr>`).join(''):'<tr><td colspan="6">No existen saldos vencidos.</td></tr>';
  }
  document.addEventListener('click',e=>{const b=e.target.closest('.tab[data-view="flujo"]');if(b)setTimeout(load,0)});window.loadFlujoCaja=load;
})();